### ISSUE TITLE
Incorrect/mixed up declensions of cases

### ISSUE THREAD

**Issue by Sohoryo** [unimorph/kaz#1]
The following entries marked LOC should actually be ACC:

бала	балаларды	N;LOC;PL
бала	баланы	N;LOC;SG
бала	баланы	N;LOC;SG
жолбарыс	жолбарыстарды	N;LOC;PL
жолбарыс	жолбарысты	N;LOC;SG
тұрғын	тұрғындарды	N;LOC;PL
тұрғын	тұрғынды	N;LOC;SG
қабір	қабілерде	N;LOC;PL
Үркер	Үркерді	N;LOC;SG

The following labeled ACC should be LOC:

бала	балаларда	N;ACC;PL
бала	балада	N;ACC;SG
жолбарыс	жолбарыстарда	N;ACC;PL
жолбарыс	жолбарыста	N;ACC;SG
тұрғын	тұрғындарда	N;ACC;PL
тұрғын	тұрғында	N;ACC;SG
Үркер	Үркерде	N;ACC;SG

The following DAT endings should be ге instead of ке:

жел	желдерке	N;DAT;PL
сәбіз	сәбіздерке	N;DAT;PL
тіл	тілдерке	N;DAT;PL

The following GEN endings should be дің/дың instead of нің/ның:

жел	желнің	N;GEN;SG
кальмар	кальмарның	N;GEN;SG

**Comment by kbatsuren** [comment]
@Sohoryo, thanks for raising issues, but for the `kaz.noun.tsv` contains the exact data that you are referring to as correct.

![image](https://user-images.githubusercontent.com/50955407/157360158-737cd447-b4de-4379-aa10-7e55937627bc.png)

If you find these mistakes from `kaz` file, I assume that we should delete this file since other data files have more instances as well as more correct.

**Comment by Sohoryo** [comment]
Correct, these mistakes were from the kaz file. They showed up while validating unimorph.

**Comment by kbatsuren** [comment]
Okay, then you can close this issue if you don't find any mistakes from other files. :)
